import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} min-h-screen h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main className="flex-1">
          <div className="flex flex-1 items-center justify-center bg-zinc-50 font-sans min-h-screen py-16">{children}</div>
        </main>
      </body>
    </html>
  );
}
